import { defineConfig } from "tsup";
import cssModulesPlugin from "esbuild-css-modules-plugin";

export default defineConfig({
  entry: {
    index: "./src/index.css",
    switcher: "./src/Components/Main-Components/switcher.tsx",
    button: "./src/Components/Main-Components/button.tsx",
    "user-nav": "./src/Components/Main-Components/user-nav.tsx",
    textarea: "./src/Components/Main-Components/textarea.tsx",
    "user-input": "./src/Components/Main-Components/user-input.tsx",
    selector: "./src/Components/Main-Components/selector.tsx",
    sidebar: "./src/Components/Main-Components/sidebar.tsx",
    "card-wrapper": "./src/Components/Main-Components/card-wrapper.tsx",
    "business-card": "./src/Components/Main-Components/business-card.tsx",
    "search-input": "./src/Components/Main-Components/search-input.tsx",
    "input-file": "./src/Components/Main-Components/input-file.tsx",
    status: "./src/Components/Main-Components/status.tsx",
    "user-profile": "./src/Components/Main-Components/user-profile.tsx",
    "navigation-trail": "./src/Components/Main-Components/navigation-trail.tsx",
    input: "./src/Components/input.tsx",
    DropDown: "./src/Components/Main-Components/DropDown.tsx",
    MainTabel: "./src/Components/Main-Components/MainTabel.tsx",
    PaginationComponent: "./src/Components/Main-Components/PaginationComponent.tsx",
    Login: "./src/Components/Main-Components/Login.tsx",
  },
  format: ["esm", "cjs"],
  minify: true,
  clean: true,
  dts: true,
  splitting: true,
  treeshake: true,
  plugins: [cssModulesPlugin()],
  external: ["react", "react-dom"],
});
